name: build dotnet
on:
  push:
    branches:
      - netfx
      
jobs:
  build:

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
      - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
      - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      
      - name: Restore Packages
      run: nuget restore ./yafsrc/YAF.NET-SqlServer.sln
      
      - name: Build solution
      run: msbuild ./yafsrc/YAF.NET-SqlServer.sln -t:rebuild -property:Configuration=Release