name: YAF.NET 3.1.x build

on:
  push:
    branches: netfx

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore Packages
      run: nuget restore ./yafsrc/YAF.NET-SqlServer.sln

    - name: Build Solution
      run: msbuild ./yafsrc/YAF.NET-SqlServer.sln -t:rebuild -property:Configuration=Release