name: YAF.NET v4 (.NET v8)
on:
  push:
    branches:
      - master
      
jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node Packages
        working-directory: ./yafsrc/YetAnotherForum.NET
        run: dotnet restore ./yafsrc/YAF.NET-SqlServer.sln
      - name: Install dependencies
        run: dotnet restore ./yafsrc/YAF.NET-SqlServer.sln
      - name: Build
        run: dotnet build ./yafsrc/YAF.NET-SqlServer.sln
      - name: Test
        run: dotnet test ./yafsrc/YAF.NET-SqlServer.sln